/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeriatt;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.TimerTask;
import java.util.Timer;

/**
 *
 * @author ITUOM
 */
public class GuiPantallaInicial extends javax.swing.JFrame {

    private List<Pedido> pedidos = new ArrayList<>();

    public GuiPantallaInicial() {
        initComponents();
        iniciarTimer();
        this.getContentPane().setBackground(Color.getHSBColor(222, 184, 135));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING : Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonDePedido = new javax.swing.JButton();
        textocliente = new javax.swing.JLabel();
        textohorapedido = new javax.swing.JLabel();
        textotiempodemora = new javax.swing.JLabel();
        textoPedido = new javax.swing.JLabel();
        Cliente1 = new javax.swing.JLabel();
        Cliente2 = new javax.swing.JLabel();
        Cliente3 = new javax.swing.JLabel();
        Cliente4 = new javax.swing.JLabel();
        Cliente5 = new javax.swing.JLabel();
        Pedido1 = new javax.swing.JLabel();
        Pedido2 = new javax.swing.JLabel();
        Pedido4 = new javax.swing.JLabel();
        Pedido5 = new javax.swing.JLabel();
        Pedido3 = new javax.swing.JLabel();
        Horapedido1 = new javax.swing.JLabel();
        Horapedido2 = new javax.swing.JLabel();
        Horapedido5 = new javax.swing.JLabel();
        Horapedido3 = new javax.swing.JLabel();
        Tiempodemora1 = new javax.swing.JLabel();
        Tiempodemora2 = new javax.swing.JLabel();
        Tiempodemora3 = new javax.swing.JLabel();
        Tiempodemora4 = new javax.swing.JLabel();
        Tiempodemora5 = new javax.swing.JLabel();
        Horapedido4 = new javax.swing.JLabel();
        jButtonEntregado1 = new javax.swing.JButton();
        jButtonEntregado2 = new javax.swing.JButton();
        jButtonEntregado3 = new javax.swing.JButton();
        jButtonEntregado4 = new javax.swing.JButton();
        jButtonEntregado5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonDePedido.setText("CREAR PEDIDO");
        botonDePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarPedido(evt);
            }
        });

        textocliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textocliente.setText("Cliente");

        textohorapedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textohorapedido.setText("Hora pedido");

        textotiempodemora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textotiempodemora.setText("Tiempo Demora");

        textoPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPedido.setText("    Pedido");

        Cliente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Cliente2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Cliente3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Cliente4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Cliente5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Pedido1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Pedido2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Pedido4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Pedido5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Pedido3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Horapedido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horapedido1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Horapedido2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horapedido2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Horapedido5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horapedido5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Horapedido3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horapedido3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tiempodemora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempodemora1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tiempodemora2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempodemora2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tiempodemora2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Tiempodemora3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempodemora3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tiempodemora4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempodemora4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tiempodemora5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempodemora5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Horapedido4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horapedido4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonEntregado1.setText("Entregado");
        jButtonEntregado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnEntregado1(evt);
            }
        });

        jButtonEntregado2.setText("Entregado");
        jButtonEntregado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnEntregado2(evt);
            }
        });

        jButtonEntregado3.setText("Entregado");
        jButtonEntregado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnEntregado3(evt);
            }
        });

        jButtonEntregado4.setText("Entregado");
        jButtonEntregado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnEntregado4(evt);
            }
        });

        jButtonEntregado5.setText("Entregado");
        jButtonEntregado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnEntregado5(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Cliente3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Cliente2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Cliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Cliente4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Cliente5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(textocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Pedido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pedido3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(Pedido2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pedido4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pedido5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textohorapedido, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Horapedido5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Horapedido4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Horapedido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Horapedido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Horapedido3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Tiempodemora1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Tiempodemora2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tiempodemora3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Tiempodemora4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(Tiempodemora5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(textotiempodemora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEntregado2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jButtonEntregado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEntregado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEntregado4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEntregado5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonDePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonDePedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textohorapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textotiempodemora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pedido2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Horapedido1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(Tiempodemora1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(jButtonEntregado1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tiempodemora2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Horapedido2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEntregado2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tiempodemora3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEntregado3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Horapedido3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tiempodemora4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEntregado4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Horapedido4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tiempodemora5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Horapedido5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEntregado5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pedido3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pedido4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pedido5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarPedido(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarPedido
        GuiPantallaPedido unPedido = new GuiPantallaPedido();
        unPedido.setPantallaListado(this);
        unPedido.setVisible(true);
    }//GEN-LAST:event_generarPedido

    private void ClickEnEntregado1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnEntregado1
        Cliente1.setText("");
        Pedido1.setText("");
        Horapedido1.setText("");
        Tiempodemora1.setText("");
    }//GEN-LAST:event_ClickEnEntregado1

    private void ClickEnEntregado2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnEntregado2
        Cliente2.setText("");
        Pedido2.setText("");
        Horapedido2.setText("");
        Tiempodemora2.setText("");
    }//GEN-LAST:event_ClickEnEntregado2

    private void ClickEnEntregado3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnEntregado3
        Cliente3.setText("");
        Pedido3.setText("");
        Horapedido3.setText("");
        Tiempodemora3.setText("");
    }//GEN-LAST:event_ClickEnEntregado3

    private void ClickEnEntregado4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnEntregado4
        Cliente4.setText("");
        Pedido4.setText("");
        Horapedido4.setText("");
        Tiempodemora4.setText("");
    }//GEN-LAST:event_ClickEnEntregado4

    private void ClickEnEntregado5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnEntregado5
        Cliente5.setText("");
        Pedido5.setText("");
        Horapedido5.setText("");
        Tiempodemora5.setText("");
    }//GEN-LAST:event_ClickEnEntregado5

    private void iniciarTimer() {
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                for (int i = 0; i < pedidos.size(); i++) {
                    Pedido pedidoActual = pedidos.get(i);
                    if (pedidoActual.estaAtrasado(new Date())) {
                        if (i == 0) {
                            Tiempodemora1.setForeground(Color.red);
                            java.awt.Toolkit.getDefaultToolkit().beep();
                        } else if (i == 1) {
                            Tiempodemora2.setForeground(Color.red);
                            java.awt.Toolkit.getDefaultToolkit().beep();
                        } else if (i == 2) {
                            Tiempodemora3.setForeground(Color.red);
                            java.awt.Toolkit.getDefaultToolkit().beep();
                        } else if (i == 3) {
                            Tiempodemora4.setForeground(Color.red);
                            java.awt.Toolkit.getDefaultToolkit().beep();
                        } else if (i == 4) {
                            Tiempodemora5.setForeground(Color.red);
                            java.awt.Toolkit.getDefaultToolkit().beep();
                        }
                    }
                }
            }
        };

        Timer timer = new Timer();
        timer.schedule(task, 0, 1000);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cliente1;
    private javax.swing.JLabel Cliente2;
    private javax.swing.JLabel Cliente3;
    private javax.swing.JLabel Cliente4;
    private javax.swing.JLabel Cliente5;
    private javax.swing.JLabel Horapedido1;
    private javax.swing.JLabel Horapedido2;
    private javax.swing.JLabel Horapedido3;
    private javax.swing.JLabel Horapedido4;
    private javax.swing.JLabel Horapedido5;
    private javax.swing.JLabel Pedido1;
    private javax.swing.JLabel Pedido2;
    private javax.swing.JLabel Pedido3;
    private javax.swing.JLabel Pedido4;
    private javax.swing.JLabel Pedido5;
    private javax.swing.JLabel Tiempodemora1;
    private javax.swing.JLabel Tiempodemora2;
    private javax.swing.JLabel Tiempodemora3;
    private javax.swing.JLabel Tiempodemora4;
    private javax.swing.JLabel Tiempodemora5;
    private javax.swing.JButton botonDePedido;
    private javax.swing.JButton jButtonEntregado1;
    private javax.swing.JButton jButtonEntregado2;
    private javax.swing.JButton jButtonEntregado3;
    private javax.swing.JButton jButtonEntregado4;
    private javax.swing.JButton jButtonEntregado5;
    private javax.swing.JLabel textoPedido;
    private javax.swing.JLabel textocliente;
    private javax.swing.JLabel textohorapedido;
    private javax.swing.JLabel textotiempodemora;
    // End of variables declaration//GEN-END:variables

    public void agregarPedido(Pedido pedidoRealizado) {
        this.pedidos.add(pedidoRealizado);
        int posicion = this.pedidos.size();
        String[] partes = pedidoRealizado.getHoraPedido().split(":");
        String hora = partes[0];
        String minutos = partes[1];
        String demora = String.valueOf(pedidoRealizado.getTiempoDemora());
        if (posicion == 1) {
            Cliente1.setText(pedidoRealizado.getCliente());
            Horapedido1.setText(hora + " : " + minutos);
            Tiempodemora1.setText(demora);
            Pedido1.setText(pedidoRealizado.getUnaPizza().getVariedadPizza().getNombre() + ", "
                    + pedidoRealizado.getUnaPizza().getTamanio() + ", " + pedidoRealizado.getUnaPizza().getTipo()
                    + ", cantidad " + pedidoRealizado.getCantidad());
        } else if (posicion == 2) {
            Cliente2.setText(pedidoRealizado.getCliente());
            Horapedido2.setText(hora + " : " + minutos);
            Tiempodemora2.setText(demora);
            Pedido2.setText(pedidoRealizado.getUnaPizza().getVariedadPizza().getNombre() + ", "
                    + pedidoRealizado.getUnaPizza().getTamanio() + ", " + pedidoRealizado.getUnaPizza().getTipo()
                    + ", cantidad " + pedidoRealizado.getCantidad());
        } else if (posicion == 3) {
            Cliente3.setText(pedidoRealizado.getCliente());
            Horapedido3.setText(hora + " : " + minutos);
            Tiempodemora3.setText(demora);
            Pedido3.setText(pedidoRealizado.getUnaPizza().getVariedadPizza().getNombre() + ", "
                    + pedidoRealizado.getUnaPizza().getTamanio() + ", " + pedidoRealizado.getUnaPizza().getTipo()
                    + ", cantidad " + pedidoRealizado.getCantidad());
        } else if (posicion == 4) {
            Cliente4.setText(pedidoRealizado.getCliente());
            Horapedido4.setText(hora + " : " + minutos);
            Tiempodemora4.setText(demora);
            Pedido4.setText(pedidoRealizado.getUnaPizza().getVariedadPizza().getNombre() + ", "
                    + pedidoRealizado.getUnaPizza().getTamanio() + ", " + pedidoRealizado.getUnaPizza().getTipo()
                    + ", cantidad " + pedidoRealizado.getCantidad());
        } else if (posicion == 5) {
            Cliente5.setText(pedidoRealizado.getCliente());
            Horapedido5.setText(hora + " : " + minutos);
            Tiempodemora5.setText(demora);
            Pedido5.setText(pedidoRealizado.getUnaPizza().getVariedadPizza().getNombre() + ", "
                    + pedidoRealizado.getUnaPizza().getTamanio() + ", " + pedidoRealizado.getUnaPizza().getTipo()
                    + ", cantidad " + pedidoRealizado.getCantidad());
        }

    }
}
